# Generated by Django 3.1 on 2020-08-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artile',
            new_name='Article',
        ),
    ]
